# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eleve/Bureau/TPBatailleNavale

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eleve/Bureau/TPBatailleNavale

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eleve/Bureau/TPBatailleNavale/CMakeFiles /home/eleve/Bureau/TPBatailleNavale/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eleve/Bureau/TPBatailleNavale/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TPBatailleNavale

# Build rule for target.
TPBatailleNavale: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TPBatailleNavale
.PHONY : TPBatailleNavale

# fast build rule for target.
TPBatailleNavale/fast:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/build
.PHONY : TPBatailleNavale/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

src/Bateau.o: src/Bateau.cpp.o

.PHONY : src/Bateau.o

# target to build an object file
src/Bateau.cpp.o:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/Bateau.cpp.o
.PHONY : src/Bateau.cpp.o

src/Bateau.i: src/Bateau.cpp.i

.PHONY : src/Bateau.i

# target to preprocess a source file
src/Bateau.cpp.i:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/Bateau.cpp.i
.PHONY : src/Bateau.cpp.i

src/Bateau.s: src/Bateau.cpp.s

.PHONY : src/Bateau.s

# target to generate assembly for a file
src/Bateau.cpp.s:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/Bateau.cpp.s
.PHONY : src/Bateau.cpp.s

src/Terrain.o: src/Terrain.cpp.o

.PHONY : src/Terrain.o

# target to build an object file
src/Terrain.cpp.o:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/Terrain.cpp.o
.PHONY : src/Terrain.cpp.o

src/Terrain.i: src/Terrain.cpp.i

.PHONY : src/Terrain.i

# target to preprocess a source file
src/Terrain.cpp.i:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/Terrain.cpp.i
.PHONY : src/Terrain.cpp.i

src/Terrain.s: src/Terrain.cpp.s

.PHONY : src/Terrain.s

# target to generate assembly for a file
src/Terrain.cpp.s:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/Terrain.cpp.s
.PHONY : src/Terrain.cpp.s

src/lib.o: src/lib.cpp.o

.PHONY : src/lib.o

# target to build an object file
src/lib.cpp.o:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/lib.cpp.o
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/lib.cpp.o
.PHONY : src/lib.cpp.o

src/lib.i: src/lib.cpp.i

.PHONY : src/lib.i

# target to preprocess a source file
src/lib.cpp.i:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/lib.cpp.i
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/lib.cpp.i
.PHONY : src/lib.cpp.i

src/lib.s: src/lib.cpp.s

.PHONY : src/lib.s

# target to generate assembly for a file
src/lib.cpp.s:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/lib.cpp.s
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/lib.cpp.s
.PHONY : src/lib.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/TPBatailleNavale.dir/build.make CMakeFiles/TPBatailleNavale.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/gtests.o: tests/gtests.cpp.o

.PHONY : tests/gtests.o

# target to build an object file
tests/gtests.cpp.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/gtests.cpp.o
.PHONY : tests/gtests.cpp.o

tests/gtests.i: tests/gtests.cpp.i

.PHONY : tests/gtests.i

# target to preprocess a source file
tests/gtests.cpp.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/gtests.cpp.i
.PHONY : tests/gtests.cpp.i

tests/gtests.s: tests/gtests.cpp.s

.PHONY : tests/gtests.s

# target to generate assembly for a file
tests/gtests.cpp.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/gtests.cpp.s
.PHONY : tests/gtests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TPBatailleNavale"
	@echo "... run_tests"
	@echo "... src/Bateau.o"
	@echo "... src/Bateau.i"
	@echo "... src/Bateau.s"
	@echo "... src/Terrain.o"
	@echo "... src/Terrain.i"
	@echo "... src/Terrain.s"
	@echo "... src/lib.o"
	@echo "... src/lib.i"
	@echo "... src/lib.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/gtests.o"
	@echo "... tests/gtests.i"
	@echo "... tests/gtests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

